sudo: required
language: c++
services:
  - docker

before_install:
  - docker pull trusch/susi-builder:stable

script:
  - docker run -v $(pwd):/src trusch/susi-builder:stable
  - cp build/*.deb ./susi-duktape-${TRAVIS_BRANCH}-linux-amd64.deb
  - docker run -v $(pwd):/opt/rootfs/src trusch/susi-arm-builder:stable
  - cp build/*.deb ./susi-duktape-${TRAVIS_BRANCH}-linux-armhf.deb

deploy:
  provider: releases
  file:
    - "susi-duktape-${TRAVIS_BRANCH}-linux-amd64.deb"
    - "susi-duktape-${TRAVIS_BRANCH}-linux-armhf.deb"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: mDzWwtPzDy+SLRDqMX88gRcwqqdTA18HUPLhr+fzWeo5OC5lAqa4GmiYRPR2kHrKfUGPWAa6Rj/LYowQD3waVxuq5jfb3zUBC+GwkSzyjTn3ju/Rstwgpbh0L9MXL+vYw2721w9cIlgzyM3xyci+W3f9og+1EryCJicLb4tZx3LxZIVFlSCRUvMLLBRDZKWXqREVaqTRG+PHhU2uKrfBYONZtBXuYqHiudiyiOWOH4zntIXzqWnMtHe77wl8kRo7Fie17QikNRGpYJUJjiuCBbp4sM3Tm8mQYeUqSIMfDmMoe3vl7+sV+I09mQ7Wb3WmN1A7W4bdwJ6jrQsWOvKeG7NHHqmaTNXdj/nDYx8R4pMh2RDp71oHUHhIoZtlpNSNxeNSf0ZtFHk4hrcEWqW9Dmjv/TkLxSN5k4sVY+3A49bKCLbqDuWkO8Tp9OFGsk4uKzORRKLTtFKzVpwm6z/mBOxOQ/9DpWBixOfRZ6rRCvYRegfzJB6s47eWAxyxNJI543TQTGTkdSylva/3uaVeMmamW1oQW90pzGBvol23LK4SCCbWKS3NO+xD1SX5gOEeHrm7R3KcxM+25QYSlKH7HXrD4b0ZmJQ7INuoX/7y2T5m7jLCKvff0ZJXZHuIQ22g8WfzNt4qeCAttS37afD+lgsuBOjFPUeMe2US62NseFs=
